### ISSUE TITLE
console/log spam

### ISSUE THREAD

**Issue by Guybrush0** [zacharied/FFXIV-Plugin-HudManager#27]
getting spammed with multiple of these a second, tried to use a fresh config didn't fix, latest version, most recent log was 1gb because of this:

```
09:58:17.817 | ERR Exception while dispatching Framework::Update event.
System.InvalidOperationException: Static pointer for FateManager::Instance is null. Did you forget to call Resolver.Initialize?
   at FFXIVClientStructs.FFXIV.Client.Game.Fate.FateManager.Instance() in D:\a\Dalamud\Dalamud\lib\FFXIVClientStructs\FFXIVClientStructs\FFXIVClientStructs.Generators\FFXIVClientStructs.Generators.StaticAddressGenerator.StaticAddressGenerator\FFXIVClientStructs.FFXIV.Client.Game.Fate.FateManager.StaticAddresses.generated.cs:line 11
   at HUD_Manager.Statuses.IsInFate(Character player) in C:\Users\zachd\Code\HUDManager-Fresh2\HUD Manager\Statuses.cs:line 156
   at HUD_Manager.StatusExtensions.Active(Status status, Plugin plugin, Character player) in C:\Users\zachd\Code\HUDManager-Fresh2\HUD Manager\Statuses.cs:line 360
   at HUD_Manager.Statuses.Update(Character player) in C:\Users\zachd\Code\HUDManager-Fresh2\HUD Manager\Statuses.cs:line 91
   at HUD_Manager.Swapper.OnFrameworkUpdate(Framework framework) in C:\Users\zachd\Code\HUDManager-Fresh2\HUD Manager\Swapper.cs:line 64
   at Dalamud.Game.Framework.HandleFrameworkUpdate(IntPtr framework) in C:\goatsoft\companysecrets\dalamud\Game\Framework.cs:line 269
```

**Comment by zacharied** [comment]
Can you do the following:
* uninstall hudmanager (your plugin will be saved)
* go to the "releases" section on the right side of the main repo page here
* download the latest release and extract it to `%AppData\XIVLauncher\devPlugins`
and verify that the logspam has been fixed?

**Comment by Guybrush0** [comment]
seems to be fixed now, no more console spam, odd issue that causes the jobs to be hidden/removed, but otherwise they worked after reassigning them
